sdras/array-explorer

store/es/index.js
This doesn't finish the job.
The components have English text inside.
Texts should be outsourced.
It's a breakthrough anyway.
=> spanish docs

store/de/index.js
Adds a German version for index.js.
=> German index.js

store/fr/index.js
French translations (waiting for #11 in order to finish all translations including templates).
=> French translation

package.json, src/App.vue, src/components/AppMethodPrimary.vue, src/components/LocaleSwitcher.vue, src/components/methods/MethodChoice.vue, src/locale/ar/index.js, src/locale/de/index.js, src/locale/en/index.js, src/locale/es/index.js, src/locale/fr/index.js, store/ar/index.js, store/ar/meta.json, store/de/index.js, store/de/meta.json, store/en/index.js, store/en/meta.json, store/es/index.js, store/es/meta.json, store/fr/index.js, store/fr/meta.json, store/index.js, yarn.lock
Please have a look at my locale switcher and review.
What have I changed/added:
- Added i18n to almost any text of the app (only the subtitle is not added yet) - it's in directory `src/locale`. Just German translation added yet. But the German translations could be probably improved (quickly translated).
- For i18n I needed to change the v-if-else cases to array access `options[0] ...` instead of direct name comparison in `AppMethodPrimary`. Please verify that I haven't messed the order / functionality here. (It should be OK but a typo with the index could happen easily here.)
- Added a way to switch between the different stores (see more details below)
- Added a simple component with a select box to change the `curLanguage` in the store. (Not styled yet.)
- Added a `meta.json` file to …
=> Added locale switcher & localized more texts.

package.json, src/App.vue, src/components/AppMethodPrimary.vue, src/components/LocaleSwitcher.vue, src/components/methods/MethodChoice.vue, src/locale/ar/index.js, src/locale/de/index.js, src/locale/en/index.js, src/locale/es/index.js, src/locale/fr/index.js, src/locale/pt/index.js, store/ar/index.js, store/ar/meta.json, store/de/index.js, store/de/meta.json, store/en/index.js, store/en/meta.json, store/es/index.js, store/es/meta.json, store/fr/index.js, store/fr/meta.json, store/index.js, store/pt/index.js, store/pt/meta.json, yarn.lock
This PR adds the Localization for Portuguese. 
It can be reviewed/merged after this PR (#22) be merged
=> L10n for Portuguese

src/locale/id/index.js, store/id/index.js, store/id/meta.json, store/index.js
I've added Indonesian translation. Let me know if you need anything else :) 
Thanks for this awesome resource!
=> Add Indonesian translation

package-lock.json, src/locale/nl/index.js, store/index.js, store/nl/index.js, store/nl/meta.json
Hi Sarah,
I've added the dutch translation (Netherlands) for this project. If I missed something, please let me know :)
Happy new year and thanks for this project!
=> Dutch translation

store/zh_cn/index.js
According to changes: https://github.com/sdras/array-explorer/commit/5ed6951c74a64ea77174d08e4023fe2e33cb1422 and https://github.com/sdras/array-explorer/commit/3f7cf39265c70f52665e06853580092c27a3cfe5
BTW, maybe we can ask other translators to update other languages?
@salahaa1 @imbyurhan @xgebi @bahe007 @AWolf81 @Gonzalo2310 @julienmartin @galuhsahid @glenngijsberts @welll @TheElderMindseeker @bdimitrovski
=> Update Chinese translation

src/locale/nl/index.js
=> Fix typo in Dutch locale

store/cz/index.js
Updated Czech translations for slice() and sort() after reading: https://github.com/sdras/array-explorer/pull/52
=> Czech update

store/sr/index.js
Updates SR translations for `Array.prototype.sort()` and `Array.prototype.slice()`
=> Update Serbian translation for Array.prototype.sort() and Array.prototype.slice()

store/id/index.js
Updated the Indonesian translation for changes https://github.com/sdras/array-explorer/commit/5ed6951c74a64ea77174d08e4023fe2e33cb1422 and https://github.com/sdras/array-explorer/commit/3f7cf39265c70f52665e06853580092c27a3cfe5, as described by #52. I only changed the `store/id/index.js` file.
=> Update Indonesian translation

src/locale/nl/index.js, store/nl/index.js
Updated the dutch translation for changes in 5ed6951 and 3f7cf39, as described by #52. Also updated the typo from #53.
=> Updated the dutch translation for sort and slice

src/locale/it/index.js, store/index.js, store/it/index.js, store/it/meta.json
This PR already includes the changes from 5ed6951c74a64ea77174d08e4023fe2e33cb1422 and 3f7cf39265c70f52665e06853580092c27a3cfe5
=> Add Italian translation

README.md
Hi Sarah!
* Thank you so much for this! I am learning Javascript now and this will definitely come in handy.
* Inspired by your project, I created a [Ruby Array Explorer](https://contrepoint.github.io/ruby-array-explorer/). Code [here](https://github.com/contrepoint/ruby-array-explorer).
* I've linked my project to your readme - let me know whether I should add anything else to other files. Please feel free to reformat and/or edit my change to fit your standards.
* It is currently a static responsive site. I will start learning Vue this weekend. Hopefully, after learning how to port this to Vue, it will be easier to set up translations, css, data, and so forth.
* Finally, I [tweeted](https://twitter.com/contrepoint21/status/948219645604929536) about the project and tagged you in it.
* …
=> Add link to Ruby Array Explorer

src/locale/bg/index.js
Let the strings flow as a single unbroken sentence.
=> Improve BG translations quality

store/fr/index.js
=> Update French translation

README.md
Hey @sdras, I added `learn-ramda` project as you suggested
Thanks!
=> docs(README): Add ramdajs in Similar Projects

src/locale/ja/index.js, store/index.js, store/ja/index.js, store/ja/meta.json
Hi, I found this Array Explorer soooo helpful and added Japanese translation.
I would appreciate if you could review it.  Thanks!
=> Add Japanese translation

src/locale/de/index.js, store/de/index.js, store/de/meta.json
german translation: fix gender of array and other glitches
=> german translation: fix gender of array and other glitches 

.editorconfig, src/locale/fi/index.js, store/fi/index.js, store/fi/meta.json, store/index.js
Hi Sarah,
I added Finnish translations for this project! This an awesome tool (I use it all the time), thank you so much for creating it!
Also added the quote type to .editorconfig, you say in README.md that single quotes are used.
=> Add finnish translations and quote type to .editorconfig
